### ISSUE TITLE
(temporary) login captcha (via commands)

### ISSUE THREAD

**Issue by 0x17de** [AndrewBelt/hack.chat#110]
How about some login captcha that could be temporarily enabled when users do some mass join via VPN/Tor and spam via login messages or chat?
Basic idea: After sending the login form data the websocket server could answer with some link/token to a captcha, which has to be solved before the actual join.

**Comment by AndrewBelt** [comment]
No sorry, too complicated, we'll just have to deal with it. Blocking Tor is an option, but many people wouldn't like that.

**Comment by ThePlatzhalter** [comment]
What kind of excuse is "too complicated"?

**Comment by raf924** [comment]
Sure that might not help hack.chat gain any popularity awards, but I don't think it was ever going to. There's so few of us who truly appreciate it.

**Comment by AndrewBelt** [comment]
The codebase is meant to be easy to modify and install for people that want to hack onto it. A few forks have been made for this reason. It has a few dozen other installations I'm aware because users like the simplicity with minimal dependencies. Feel free to fork it though and host your own. You could take off with it.

**Comment by ToastyStoemp** [comment]
There could be a difference between Hack.Chat you are hosting and Hack.Chat on github

**Comment by raf924** [comment]
yep you could hack onto it yourself
