### ISSUE TITLE
Off-the-Record encryption

### ISSUE THREAD

**Issue by jinformatique** [AndrewBelt/hack.chat#4]
Would be nice to have encryption by default like OTR.

There is a library here:
Off-the-Record Messaging Protocol implemented in JavaScript
https://arlolra.github.io/otr/

**Comment by AndrewBelt** [comment]
Most people will complain about in-browser encryption if they notice it (even if it's neutral for their security, I don't know why. I guess because it gives a false sense of security to those less aware.) HTTPS is forced on https://hack.chat/, so your session is safe from man-in-the-middle attacks. However, if the main server is compromised, an attacker can send modified Javascript to bypass and make OTR libraries essentially useless.

**Comment by jinformatique** [comment]
That's odd people complaining about security features. If I asked for it, it was in order to host on my own server.

**Comment by AndrewBelt** [comment]
Oh, I see. In that case, forcing HTTPS with an HTTP proxy would solve the problem if you assume you have control over your own server, right?
